---
kube_version: "1.18.0-00"

k8s_packages:
- "kubeadm"
- "kubectl"
- "kubelet"

package_versions:
  kubeadm: "{{ kube_version }}"
  kubectl: "{{ kube_version }}"
  kubelet: "{{ kube_version }}"

reset: false
cluster: ""

master_port: 6443

pod_network_cidr: "10.244.0.0/16"

cni: "weave"

cni_init_extra:
  flannel: "--pod-network-cidr={{ pod_network_cidr }}"
  weave: "--pod-network-cidr={{ pod_network_cidr }}"
