---
- name: Enable Flannel CNI
  shell: "curl -sSL https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml | kubectl create -f -"
    warn: no
  register: cni_out

- debug: var=cni_out

- name: Wait for the Flannel CNI pods to stabalize
  shell: kubectl get pods --namespace=kube-system | grep kube-flannel | grep Running | wc -l
  register: cni_test
  until: cni_test.stdout|int > 0
  retries: 12
  delay: 10

- name: Wait for the DNS pods to stabalize
  shell: kubectl get pods --namespace=kube-system | grep coredns | grep Running | wc -l
  register: dns_test
  until: dns_test.stdout|int > 0
  retries: 12
  delay: 10
