---
- hosts: all
  tasks:
    - name: apt-get update && apt-get upgrade
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 0
    - name: Reboot host
      shell: sleep 2 && /sbin/shutdown -r now "Ansible reboot"
      async: 1
      poll: 0
    - name: Wait for host to come back up
      become: false
      wait_for_connection:
        delay: 15
        sleep: 2
        timeout: 120
